# Generated by Django 5.2.6 on 2025-09-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViaCep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=225)),
                ('bairro', models.CharField(max_length=225)),
                ('cidade', models.CharField(max_length=225)),
                ('estado', models.CharField(max_length=225)),
                ('cep', models.CharField(max_length=225)),
            ],
        ),
    ]
